# gh-api
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-api.1.gz
complete -c gh-api -l field -d 'In --paginate mode, all pages of results will sequentially be requested until…'
complete -c gh-api -l cache -d '	Cache the response, e. g.  "3600s", "60m", "1h"'
complete -c gh-api -s F -d '	Add a typed parameter in key=value format'
complete -c gh-api -s H -l header -d '	Add a HTTP request header in key:value format'
complete -c gh-api -l hostname -d '	The GitHub hostname for the request (default "github. com")'
complete -c gh-api -s i -l include -d '	Include HTTP response headers in the output'
complete -c gh-api -l input -d '	The file to use as body for the HTTP request'
complete -c gh-api -s q -l jq -d '	Query to select values from the response using jq syntax'
complete -c gh-api -s X -l method -d '	The HTTP method for the request'
complete -c gh-api -l paginate -d '	Make additional HTTP requests to fetch all pages of results'
complete -c gh-api -s p -l preview -d '	Opt into GitHub API previews'
complete -c gh-api -s f -l raw-field -d '	Add a string parameter in key=value format'
complete -c gh-api -l silent -d '	Do not print the response body'
complete -c gh-api -s t -l template -d '	Format the response using a Go template OPTIONS INHERITED FROM PARENT COMMAN…'
complete -c gh-api -l help -d '	Show help for command EXAMPLE # list releases in the current repository $ gh…'

