# gh-auth-logout
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-auth-logout.1.gz
complete -c gh-auth-logout -s h -l hostname -d '	The hostname of the GitHub instance to log out of OPTIONS INHERITED FROM PAR…'
complete -c gh-auth-logout -l help -d '	Show help for command EXAMPLE $ gh auth logout # => select what host to log …'

