# gh-auth-refresh
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-auth-refresh.1.gz
complete -c gh-auth-refresh -s h -l hostname -d '	The GitHub host to use for authentication'
complete -c gh-auth-refresh -s s -l scopes -d '	Additional authentication scopes for gh to have OPTIONS INHERITED FROM PAREN…'
complete -c gh-auth-refresh -l help -d '	Show help for command EXAMPLE $ gh auth refresh --scopes write:org,read:publ…'

