# gh-alias-set
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-alias-set.1.gz
complete -c gh-alias-set -s s -l shell -d '	Declare an alias to be passed through a shell interpreter OPTIONS INHERITED …'
complete -c gh-alias-set -l help -d '	Show help for command EXAMPLE # note: Command Prompt on Windows requires usi…'

