# gh-auth-login
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-auth-login.1.gz
complete -c gh-auth-login -s h -l hostname -d '	The hostname of the GitHub instance to authenticate with'
complete -c gh-auth-login -s s -l scopes -d '	Additional authentication scopes for gh to have'
complete -c gh-auth-login -s w -l web -d '	Open a browser to authenticate'
complete -c gh-auth-login -l with-token -d '	Read token from standard input OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-auth-login -l help -d '	Show help for command EXAMPLE # start interactive setup $ gh auth login'

