# gh-browse
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-browse.1.gz
complete -c gh-browse -s b -l branch -d '	Select another branch by passing in the branch name'
complete -c gh-browse -s n -l no-browser -d '	Print destination URL instead of opening the browser'
complete -c gh-browse -s p -l projects -d '	Open repository projects'
complete -c gh-browse -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format'
complete -c gh-browse -s s -l settings -d '	Open repository settings'
complete -c gh-browse -s w -l wiki -d '	Open repository wiki OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-browse -l help -d '	Show help for command EXAMPLE $ gh browse #=> Open the home page of the curr…'

