# gh-config-get
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-config-get.1.gz
complete -c gh-config-get -s h -l host -d '	Get per-host setting OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-config-get -l help -d '	Show help for command EXAMPLE $ gh config get git_protocol https SEE ALSO'

