# gh-gist-view
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-gist-view.1.gz
complete -c gh-gist-view -s f -l filename -d '	Display a single file from the gist'
complete -c gh-gist-view -l files -d '	List file names from the gist'
complete -c gh-gist-view -s r -l raw -d '	Print raw instead of rendered gist contents'
complete -c gh-gist-view -s w -l web -d '	Open gist in the browser OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-gist-view -l help -d '	Show help for command SEE ALSO'

