# gh-gist-create
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-gist-create.1.gz
complete -c gh-gist-create -s d -l desc -d '	A description for this gist'
complete -c gh-gist-create -s f -l filename -d '	Provide a filename to be used when reading from STDIN'
complete -c gh-gist-create -s p -l public -d '	List the gist publicly (default: secret)'
complete -c gh-gist-create -s w -l web -d '	Open the web browser with created gist OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-gist-create -l help -d '	Show help for command EXAMPLE # publish file \'hello'

