# gh-gist-edit
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-gist-edit.1.gz
complete -c gh-gist-edit -s a -l add -d '	Add a new file to the gist'
complete -c gh-gist-edit -s f -l filename -d '	Select a file to edit OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-gist-edit -l help -d '	Show help for command SEE ALSO'

