# gh-issue-transfer
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-issue-transfer.1.gz
complete -c gh-issue-transfer -l help -d '	Show help for command'
complete -c gh-issue-transfer -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

