# gh-issue-list
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-issue-list.1.gz
complete -c gh-issue-list -s a -l assignee -d '	Filter by assignee'
complete -c gh-issue-list -s A -l author -d '	Filter by author'
complete -c gh-issue-list -s q -l jq -d '	Filter JSON output using a jq expression'
complete -c gh-issue-list -l json -d '	Output JSON with the specified fields'
complete -c gh-issue-list -s l -l label -d '	Filter by labels'
complete -c gh-issue-list -s L -l limit -d '	Maximum number of issues to fetch'
complete -c gh-issue-list -l mention -d '	Filter by mention'
complete -c gh-issue-list -s m -l milestone -d '	Filter by milestone number or title'
complete -c gh-issue-list -s S -l search -d '	Search issues with query'
complete -c gh-issue-list -s s -l state -d '	Filter by state: {open|closed|all}'
complete -c gh-issue-list -s t -l template -d '	Format JSON output using a Go template'
complete -c gh-issue-list -s w -l web -d '	Open the browser to list the issue(s) OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-issue-list -l help -d '	Show help for command'
complete -c gh-issue-list -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format EXAMPLE $ gh is…'

