# gh-issue
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-issue.1.gz
complete -c gh-issue -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format OPTIONS INHERIT…'
complete -c gh-issue -l help -d '	Show help for command EXAMPLE $ gh issue list $ gh issue create --label bug …'

