# gh-issue-close
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-issue-close.1.gz
complete -c gh-issue-close -l help -d '	Show help for command'
complete -c gh-issue-close -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

