# gh-pr-diff
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-pr-diff.1.gz
complete -c gh-pr-diff -l color -d '	Use color in diff output: {always|never|auto} OPTIONS INHERITED FROM PARENT …'
complete -c gh-pr-diff -l help -d '	Show help for command'
complete -c gh-pr-diff -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

