# gh-pr-status
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-pr-status.1.gz
complete -c gh-pr-status -s q -l jq -d '	Filter JSON output using a jq expression'
complete -c gh-pr-status -l json -d '	Output JSON with the specified fields'
complete -c gh-pr-status -s t -l template -d '	Format JSON output using a Go template OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-pr-status -l help -d '	Show help for command'
complete -c gh-pr-status -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

