# gh-pr-comment
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-pr-comment.1.gz
complete -c gh-pr-comment -s b -l body -d '	Supply a body.  Will prompt for one otherwise'
complete -c gh-pr-comment -s F -l body-file -d '	Read body text from file'
complete -c gh-pr-comment -s e -l editor -d '	Add body using editor'
complete -c gh-pr-comment -s w -l web -d '	Add body in browser OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-pr-comment -l help -d '	Show help for command'
complete -c gh-pr-comment -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format EXAMPLE $ gh pr…'

