# gh-pr-checkout
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-pr-checkout.1.gz
complete -c gh-pr-checkout -l detach -d '	Checkout PR with a detached HEAD'
complete -c gh-pr-checkout -s f -l force -d '	Reset the existing local branch to the latest state of the pull request'
complete -c gh-pr-checkout -l recurse-submodules -d '	Update all submodules after checkout OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-pr-checkout -l help -d '	Show help for command'
complete -c gh-pr-checkout -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

