# gh-pr-ready
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-pr-ready.1.gz
complete -c gh-pr-ready -l help -d '	Show help for command'
complete -c gh-pr-ready -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

