# gh-pr-view
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-pr-view.1.gz
complete -c gh-pr-view -s c -l comments -d '	View pull request comments'
complete -c gh-pr-view -s q -l jq -d '	Filter JSON output using a jq expression'
complete -c gh-pr-view -l json -d '	Output JSON with the specified fields'
complete -c gh-pr-view -s t -l template -d '	Format JSON output using a Go template'
complete -c gh-pr-view -s w -l web -d '	Open a pull request in the browser OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-pr-view -l help -d '	Show help for command'
complete -c gh-pr-view -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

