# gh-pr-close
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-pr-close.1.gz
complete -c gh-pr-close -s d -l delete-branch -d '	Delete the local and remote branch after close OPTIONS INHERITED FROM PARENT…'
complete -c gh-pr-close -l help -d '	Show help for command'
complete -c gh-pr-close -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

