# gh-pr-merge
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-pr-merge.1.gz
complete -c gh-pr-merge -l admin -d '	Use administrator privileges to merge a pull request that does not meet requ…'
complete -c gh-pr-merge -l auto -d '	Automatically merge only after necessary requirements are met'
complete -c gh-pr-merge -s b -l body -d '	Body text for the merge commit'
complete -c gh-pr-merge -s F -l body-file -d '	Read body text from file'
complete -c gh-pr-merge -s d -l delete-branch -d '	Delete the local and remote branch after merge'
complete -c gh-pr-merge -l disable-auto -d '	Disable auto-merge for this pull request'
complete -c gh-pr-merge -s m -l merge -d '	Merge the commits with the base branch'
complete -c gh-pr-merge -s r -l rebase -d '	Rebase the commits onto the base branch'
complete -c gh-pr-merge -s s -l squash -d '	Squash the commits into one commit and merge it into the base branch OPTIONS…'
complete -c gh-pr-merge -l help -d '	Show help for command'
complete -c gh-pr-merge -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

