# gh-pr-checks
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-pr-checks.1.gz
complete -c gh-pr-checks -s w -l web -d '	Open the web browser to show details about checks OPTIONS INHERITED FROM PAR…'
complete -c gh-pr-checks -l help -d '	Show help for command'
complete -c gh-pr-checks -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

