# gh-release-list
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-release-list.1.gz
complete -c gh-release-list -s L -l limit -d '	Maximum number of items to fetch OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-release-list -l help -d '	Show help for command'
complete -c gh-release-list -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

