# gh-release
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-release.1.gz
complete -c gh-release -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format OPTIONS INHERIT…'
complete -c gh-release -l help -d '	Show help for command SEE ALSO'

