# gh-release-delete
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-release-delete.1.gz
complete -c gh-release-delete -s y -l yes -d '	Skip the confirmation prompt OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-release-delete -l help -d '	Show help for command'
complete -c gh-release-delete -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

