# gh-repo-create
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-repo-create.1.gz
complete -c gh-repo-create -l confirm
complete -c gh-repo-create -l public -l private -l internal -d 'To toggle off --enable-issues or --enable-wiki, which are enabled by default,…'
complete -c gh-repo-create -s y -d '	Skip the confirmation prompt'
complete -c gh-repo-create -s d -l description -d '	Description of the repository'
complete -c gh-repo-create -l enable-issues -d '	Enable issues in the new repository'
complete -c gh-repo-create -l enable-wiki -d '	Enable wiki in the new repository'
complete -c gh-repo-create -s g -l gitignore -d '	Specify a gitignore template for the repository'
complete -c gh-repo-create -s h -l homepage -d '	Repository home page URL'
complete -c gh-repo-create -s l -l license -d '	Specify an Open Source License for the repository'
complete -c gh-repo-create -s t -l team -d '	The name of the organization team to be granted access'
complete -c gh-repo-create -s p -l template -d '	Make the new repository based on a template repository OPTIONS INHERITED FRO…'
complete -c gh-repo-create -l help -d '	Show help for command EXAMPLE # create a repository under your account using…'

