# gh-repo-list
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-repo-list.1.gz
complete -c gh-repo-list -l archived -d '	Show only archived repositories'
complete -c gh-repo-list -l fork -d '	Show only forks'
complete -c gh-repo-list -s q -l jq -d '	Filter JSON output using a jq expression'
complete -c gh-repo-list -l json -d '	Output JSON with the specified fields'
complete -c gh-repo-list -s l -l language -d '	Filter by primary coding language'
complete -c gh-repo-list -s L -l limit -d '	Maximum number of repositories to list'
complete -c gh-repo-list -l no-archived -d '	Omit archived repositories'
complete -c gh-repo-list -l private -d '	Show only private repositories'
complete -c gh-repo-list -l public -d '	Show only public repositories'
complete -c gh-repo-list -l source -d '	Show only non-forks'
complete -c gh-repo-list -s t -l template -d '	Format JSON output using a Go template OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-repo-list -l help -d '	Show help for command SEE ALSO'

