# gh-release-download
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-release-download.1.gz
complete -c gh-release-download -s D -l dir -d '	The directory to download files into'
complete -c gh-release-download -s p -l pattern -d '	Download only assets that match a glob pattern OPTIONS INHERITED FROM PARENT…'
complete -c gh-release-download -l help -d '	Show help for command'
complete -c gh-release-download -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # downl…'

