# gh-repo-fork
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-repo-fork.1.gz
complete -c gh-repo-fork -l clone -d '	Clone the fork {true|false}'
complete -c gh-repo-fork -l org -d '	Create the fork in an organization'
complete -c gh-repo-fork -l remote -d '	Add remote for fork {true|false}'
complete -c gh-repo-fork -l remote-name -d '	Specify a name for a fork\'s new remote'
complete -c gh-repo-fork -l help -d '	Show help for command SEE ALSO'

