# gh-repo-view
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-repo-view.1.gz
complete -c gh-repo-view -s b -l branch -d '	View a specific branch of the repository'
complete -c gh-repo-view -s q -l jq -d '	Filter JSON output using a jq expression'
complete -c gh-repo-view -l json -d '	Output JSON with the specified fields'
complete -c gh-repo-view -s t -l template -d '	Format JSON output using a Go template'
complete -c gh-repo-view -s w -l web -d '	Open a repository in the browser OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-repo-view -l help -d '	Show help for command SEE ALSO'

