# gh-run-download
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-run-download.1.gz
complete -c gh-run-download -s D -l dir -d '	The directory to download artifacts into'
complete -c gh-run-download -s n -l name -d '	Only download artifacts that match any of the given names OPTIONS INHERITED …'
complete -c gh-run-download -l help -d '	Show help for command'
complete -c gh-run-download -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # Downl…'

