# gh-release-view
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-release-view.1.gz
complete -c gh-release-view -s q -l jq -d '	Filter JSON output using a jq expression'
complete -c gh-release-view -l json -d '	Output JSON with the specified fields'
complete -c gh-release-view -s t -l template -d '	Format JSON output using a Go template'
complete -c gh-release-view -s w -l web -d '	Open the release in the browser OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-release-view -l help -d '	Show help for command'
complete -c gh-release-view -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

