# gh-repo
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-repo.1.gz
complete -c gh-repo -l help -d '	Show help for command EXAMPLE $ gh repo create $ gh repo clone cli/cli $ gh …'

