# gh-secret-remove
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-secret-remove.1.gz
complete -c gh-secret-remove -s e -l env -d '	Remove a secret for an environment'
complete -c gh-secret-remove -s o -l org -d '	Remove a secret for an organization OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-secret-remove -l help -d '	Show help for command'
complete -c gh-secret-remove -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

