# gh-secret-list
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-secret-list.1.gz
complete -c gh-secret-list -s e -l env -d '	List secrets for an environment'
complete -c gh-secret-list -s o -l org -d '	List secrets for an organization OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-secret-list -l help -d '	Show help for command'
complete -c gh-secret-list -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

