# gh-secret-set
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-secret-set.1.gz
complete -c gh-secret-set -s b -l body -d '	A value for the secret.  Reads from STDIN if not specified'
complete -c gh-secret-set -s e -l env -d '	Set a secret for an environment'
complete -c gh-secret-set -s o -l org -d '	Set a secret for an organization'
complete -c gh-secret-set -s r -l repos -d '	List of repository names for selected visibility'
complete -c gh-secret-set -s v -l visibility -d '	Set visibility for an organization secret: all, private, or selected OPTIONS…'
complete -c gh-secret-set -l help -d '	Show help for command'
complete -c gh-secret-set -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format EXAMPLE Paste s…'

