# gh-workflow-view
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-workflow-view.1.gz
complete -c gh-workflow-view -s r -l ref -d '	The branch or tag name which contains the version of the workflow file you\'d…'
complete -c gh-workflow-view -s w -l web -d '	Open workflow in the browser'
complete -c gh-workflow-view -s y -l yaml -d '	View the workflow yaml file OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-workflow-view -l help -d '	Show help for command'
complete -c gh-workflow-view -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # Inter…'

