# gh-workflow-list
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh-workflow-list.1.gz
complete -c gh-workflow-list -s a -l all -d '	Show all workflows, including disabled workflows'
complete -c gh-workflow-list -s L -l limit -d '	Maximum number of workflows to fetch OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-workflow-list -l help -d '	Show help for command'
complete -c gh-workflow-list -s R -l repo -d '	Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

