# gh
# Autogenerated from man page /data/data/com.termux/files/usr/share/man/man1/gh.1.gz
complete -c gh -l help -d '	Show help for command'
complete -c gh -l version -d '	Show gh version EXAMPLE $ gh issue create $ gh repo clone cli/cli $ gh pr ch…'

